### PR TITLE
Basic support for passing in data readers when populating from file

### PR DESCRIPTION
**Pull request by neuromantik33**
Needed for edn files which might contain reader macros such as integrant, vase etc...

### CODE REVIEW

**Comment by alexander-yakushev** [comment]
Hi, thank you for the pull request!

Here are a few comments:
- I would name the variable`*data-readers*` since `*readers*` is a bit too generic. A docstring for it would be nice too.
- The indentation of the `if` expression doesn't seem right.
- Could you please also mention this feature in this section: https://github.com/grammarly/omniconf#providing-configuration-as-files ?

**Comment by neuromantik33** [comment]
Sure thing :) I'll update the docs and correct indentation accordingly

**Comment by neuromantik33** [comment]
Done! 😊

**Comment by alexander-yakushev** [comment]
Thank you!

**Comment by alexander-yakushev** [comment]
I pushed these changes to `0.4.2-SNAPSHOT`, if you confirm it works for you, I will publish `0.4.2`.

**Comment by neuromantik33** [comment]
Besides a somewhat annoying warning message

`WARNING: *data-readers* already refers to: #'clojure.core/*data-readers* in namespace: omniconf.core, being replaced by: #'omniconf.core/*data-readers*`

it works just fine. You can release as you see fit :+1: 

Thanks!

**Comment by alexander-yakushev** [comment]
I fixed the warning and deployed `0.4.2`.

**Pull request merged**
